AWSTemplateFormatVersion: 2010-09-09

Parameters: # params passed to "--parameter-overrides" in CLI
  BucketName:
    Description: Unique name for your bucket. This will be in the S3 url to your React app.
    Type: String
    Default: cdugga-s3starter
  LandingPage:
        Description: Index.html/error.html same page if React application
        Type: String
        Default: index.html

Resources:
#   ApiGateway:
#     Type: 'AWS::ApiGateway::RestApi'
#     Properties: {}
#   Lambda:
#     Type: 'AWS::Lambda::Function'
#     Properties: {}
    
    LambdaExecutionRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                - lambda.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Path: /
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action: 
                    - logs:*
                  Resource: 
                    arn:aws:logs:*:*:*
    S3StarterLambda:
      Type: 'AWS::Lambda::Function'
      Properties:
        Handler: index.go
        Role: !Ref LambdaExecutionRole
        Runtime: go1.x
        Code:
          ZipFile: |
              import (
                  "encoding/json"

                  "github.com/aws/aws-lambda-go/events"
                  "github.com/aws/aws-lambda-go/lambda"
                  "github.com/sbstjn/go-lambda-example/repository"
                )

                func handleRequest(req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
                  
                  return events.APIGatewayProxyResponse{Body: string("success"), StatusCode: 200}, nil
                }

                func main() {
                  lambda.Start(handleRequest)
                }
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties: 
        AccessControl: PublicRead
        BucketName: { "Fn::Sub": [ "${stack}.${bucket}", { "bucket": {"Ref" : "BucketName" } , "stack": {"Ref":"AWS::StackName"}} ]} 
        VersioningConfiguration:
            Status: Suspended
        WebsiteConfiguration:
            ErrorDocument: !Ref LandingPage
            IndexDocument: !Ref LandingPage
    OpenBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket # attach to bucket being created
        PolicyDocument:
            Statement: # lets the public access/view the contents of your Bucket, i.e. web app
              - Action: 's3:GetObject'
                Effect: Allow
                Principal: '*' 
                Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, /*]]
    Distribution:
      Type: AWS::CloudFront::Distribution
      Properties: 
        DistributionConfig: 
            # CacheBehaviors:
            #     - LambdaFunctionAssociations:
            #         - EventType: string-value
            #         LambdaFunctionARN: string-value
            DefaultCacheBehavior:
                ForwardedValues:
                    QueryString: false
                    Cookies:
                      Forward: all
                ViewerProtocolPolicy: redirect-to-https
                MinTTL: 42
                TargetOriginId: s3-cloudstarter
                AllowedMethods:
                    - GET
                    - HEAD
                    - DELETE
                    - OPTIONS
                    - PATCH
                    - POST
                    - PUT
                # LambdaFunctionAssociations:
                # - EventType: string-value
                #     LambdaFunctionARN: string-value
            IPV6Enabled: false
            Enabled: true
            DefaultRootObject: index.html
            # HttpVersion: 'http2'
            Origins:
                - DomainName: cdugga-s3starter.s3-eu-west-1.amazonaws.com
                  Id: s3-cloudstarter
                  CustomOriginConfig:
                    HTTPPort: '80'
                    HTTPSPort: '443'
                    OriginProtocolPolicy: http-only
                    # OriginKeepaliveTimeout: !Ref 'OriginKeepaliveTimeout'
                    # OriginReadTimeout: !Ref 'OriginReadTimeout'
                    OriginSSLProtocols:
                      - TLSv1
                      - TLSv1.1
                      - TLSv1.2
                      - SSLv3
        #Tags: 
        #- Tag

#   CloudFrontDist:
#     Type: 'AWS::CloudFront::Distribution'
#     Properties: {}
 