AWSTemplateFormatVersion: 2010-09-09

Parameters: # params passed to "--parameter-overrides" in CLI
  BucketName:
    Description: Unique name for your bucket. This will be in the S3 url to your React app.
    Type: String
    Default: cdugga-s3starter
  LandingPage:
        Description: Index.html/error.html same page if React application
        Type: String
        Default: index.html

Resources:
#   ApiGateway:
#     Type: 'AWS::ApiGateway::RestApi'
#     Properties: {}
#   Lambda:
#     Type: 'AWS::Lambda::Function'
#     Properties: {}
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties: 
        AccessControl: PublicRead
        BucketName: !Ref BucketName
        VersioningConfiguration:
            Status: Suspended
        WebsiteConfiguration:
            ErrorDocument: !Ref LandingPage
            IndexDocument: !Ref LandingPage
   
  OpenBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
        Bucket: !Ref S3Bucket # attach to bucket being created
        PolicyDocument:
            Statement: # lets the public access/view the contents of your Bucket, i.e. web app
              - Action: 's3:GetObject'
                Effect: Allow
                Principal: '*' # wildcard, allow all requests
                Resource: !Join ['', ['arn:aws:s3:::', !Ref S3Bucket, /*]]
  
#   CloudFrontDist:
#     Type: 'AWS::CloudFront::Distribution'
#     Properties: {}
 